name: Scrape latest data
 
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'
 
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://roads.data.tfl.gov.uk/trafficstatus/vms.xml -o signs.xml
      - name: Install Python Dependencies
        run: pip install -r ./requirements.txt
      - name: Build json array from xml
        run: python ./etl.py        
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
